baseurl         = "https://francinemujinga.online/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"


[params]
  title       = "Francine Blog Page"
  subtitle    = "Life style, Poetry and You tube"
  tags = "post"

  cover       = "images/uploads/home-bg.jpg"
  description = "Blog website for my content"
  metaDescription = "Francine Blog"
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "FrancineHaay"
  fbName = "eephy.lane"
  youTubeName = "channel/UClagvd3rPOyLXS9UdFYhPow/about"
  

  logo = "https://static.vecteezy.com/system/resources/previews/000/619/336/large_2x/f-logo-and-symbols-template-vector-icons.jpg"
  orgName = "FM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "You Tube Site"

  author = "Francine"
  authorAvatar = "images/uploads/profile-picture.jpeg"
  authorLocation = "Cape Town"
  authorWebsite = "https://eueung.github.io"
  authorDescription = "You tuber, Creative Writer and Blogger"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"
  design = "/:slug"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Life Style"
  url = "/categories/life/"
  weight = 100

[[menu.main]]
  name = "Poetry"
  url = "/categories/poetry/"
  weight = 99

[[menu.main]]
  name = "You tube"
  url = "https://www.youtube.com/channel/UClagvd3rPOyLXS9UdFYhPow"
  weight = 95